import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from "next/font/google";
import Bootstrapclient from './componants/bootstrapclient';

export const metadata = {
  title: "My-App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });
import "./globals.css";
import "./componants/Footer/Footer.css"
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Bootstrapclient />
        </body>
    </html>
  );
}
